version: '3'

services:
  django-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - postgres

  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - django-backend

  postgres:
    image: postgres:latest
    env_file:
      - .env.dev
    networks:
      - default