# Generated by Django 5.0.2 on 2024-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('starting_point', models.CharField(max_length=255)),
                ('final_point', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
            ],
        ),
    ]
