# Generated by Django 5.0.2 on 2024-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='events',
            field=models.ManyToManyField(related_name='machines', to='analytics.event'),
        ),
    ]
