# Generated by Django 5.0.2 on 2024-02-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_machine_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.machine'),
        ),
    ]
