# Generated by Django 5.0.2 on 2024-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_machine_events_event_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('Installation', 'Backout'), ('Backout', 'Backout')], max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os',
            field=models.CharField(choices=[('RHEL8', 'RHEL8'), ('WRL7', 'WRL7')], max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='product_type',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], max_length=255),
        ),
    ]
