# Generated by Django 5.0.2 on 2024-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_event_name_alter_machine_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Backout', 'Backout')], max_length=255),
        ),
    ]
