# Generated by Django 5.0.2 on 2024-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='os',
            field=models.CharField(choices=[('RHEL8', 'RHEL8'), ('WRL7', 'WRL7'), ('Solaris', 'Solaris')], max_length=255),
        ),
    ]
